# Generated by Django 5.2.8 on 2025-12-15 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('under_medication', models.BooleanField(default=False)),
                ('ward', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('insurance_provider', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(default='johndoe@example.com', max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'SuperAdmin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('pharmacist', 'Pharmacist'), ('lab_technician', 'Lab Technician'), ('receptionist', 'Receptionist'), ('driver', 'Driver'), ('other', 'Other')], default='other', max_length=20)),
                ('firebase_uid', models.CharField(default='@Ambumeadow2025', max_length=256)),
                ('phone_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.URLField(blank=True, default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748119193/zzy3zwrius3kjrzp4ifc.png', null=True)),
                ('expo_token', models.CharField(default='hsvsx92jjs', max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(default='johndoe@example.com', max_length=100)),
                ('firebase_uid', models.CharField(default='@Ambumeadow2025', max_length=256)),
                ('current_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('current_lng', models.FloatField(blank=True, default=0.0, null=True)),
                ('phone_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.URLField(blank=True, default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748119193/zzy3zwrius3kjrzp4ifc.png', null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('expo_token', models.CharField(default='hsvsx92jjs', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diagnosis', models.TextField()),
                ('prescription', models.TextField()),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.staff')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.user'),
        ),
    ]
