# Generated by Django 5.2.8 on 2026-05-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
    ]
