# Generated by Django 5.2.8 on 2025-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
    ]
