# Generated by Django 5.2.8 on 2025-12-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0003_user_agreed'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('system', 'System'), ('prescription', 'Prescription'), ('update', 'Update'), ('order', 'Order')], default='update', max_length=20),
        ),
    ]
