# Generated by Django 5.2.8 on 2025-12-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0004_notification_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
