# Generated by Django 5.2.8 on 2026-05-23 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0004_careappointment_home_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careappointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.staff'),
        ),
    ]
