# Generated by Django 5.2.8 on 2025-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='id_number',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
