# Generated by Django 5.2.8 on 2025-12-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0006_staff_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='agreed',
            field=models.BooleanField(default=False),
        ),
    ]
