# Generated by Django 5.2.8 on 2026-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0006_package_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='Bronze', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(choices=[('family', 'Family'), ('individual', 'Individual')], default='Individual', max_length=100),
        ),
    ]
