# Generated by Django 5.2.8 on 2025-12-21 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0007_staff_agreed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('appointment', 'Appointment'), ('system', 'System'), ('prescription', 'Prescription'), ('update', 'Update'), ('order', 'Order')], default='update', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.staff')),
            ],
        ),
    ]
