# Generated by Django 5.2.8 on 2025-12-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0008_staffnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
