# Generated by Django 5.2.8 on 2025-12-30 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0009_alter_staff_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('emergency_contact', models.CharField(default='', max_length=20)),
                ('latitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('longitude', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(default='', max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('firebase_uid', models.CharField(default='@Ambumeadow2025', max_length=256)),
                ('phone_verified', models.BooleanField(default=False)),
                ('agreed', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_expiry', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.URLField(blank=True, default='', null=True)),
                ('expo_token', models.CharField(default='hsvsx92jjs', max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('current_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('current_lng', models.FloatField(blank=True, default=0.0, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.hospital')),
            ],
        ),
    ]
