# Generated by Django 5.2.8 on 2025-12-30 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0010_hospital_driver_ambulance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='driver_phone',
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.driver'),
            preserve_default=False,
        ),
    ]
