# Generated by Django 5.2.8 on 2025-12-30 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0011_remove_ambulance_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('emergency', 'Emergency'), ('antibiotic', 'Antibiotics'), ('pain_relief', 'Pain Relief'), ('chronic', 'Chronic Care'), ('pediatric', 'Child & Maternal'), ('digestive', 'Digestive'), ('respiratory', 'Respiratory'), ('mental_health', 'Mental Health'), ('skin', 'Skin Care'), ('supplements', 'Supplements')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('requires_prescription', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
