# Generated by Django 5.2.8 on 2026-01-02 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0015_staff_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(max_length=100)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.staff')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.user')),
            ],
        ),
    ]
