# Generated by Django 5.2.8 on 2026-01-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0016_careappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('emergency', 'Emergency'), ('radiology', 'Radiology'), ('general_medicine', 'General Medicine'), ('surgery', 'Surgery'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='staff',
            name='medical_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
