# Generated by Django 5.2.8 on 2026-01-12 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0017_staff_department_staff_medical_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
