# Generated by Django 5.2.8 on 2026-01-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0018_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
