# Generated by Django 5.2.8 on 2026-01-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0020_drivernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id_number',
            field=models.CharField(default='12345678', max_length=8),
        ),
    ]
