# Generated by Django 5.2.8 on 2026-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0021_driver_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20),
        ),
    ]
