# Generated by Django 5.2.8 on 2026-01-14 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0022_ambulance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambumeadow_app.driver'),
        ),
    ]
