# Generated by Django 5.2.8 on 2026-01-16 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0023_alter_ambulance_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('merchandise', 'Merchandise'), ('care_appointment', 'Care Appointment'), ('ambulance_booking', 'Ambulance Booking'), ('other', 'Other')], default='other', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('wallet', 'Wallet'), ('paystack', 'Paystack')], max_length=20)),
                ('receipt_number', models.CharField(default='', max_length=100)),
                ('checkout_request_id', models.CharField(default='', max_length=100)),
                ('merchant_request_id', models.CharField(default='', max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.user')),
            ],
        ),
    ]
