# Generated by Django 5.2.8 on 2026-01-16 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0024_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('booking_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.ambulance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.user')),
            ],
        ),
    ]
