# Generated by Django 5.2.8 on 2026-01-16 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambumeadow_app', '0025_ambulancebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambumeadow_app.hospital'),
        ),
    ]
